### ISSUE TITLE
mirror/http/proxy not configurable?

### ISSUE THREAD

**Issue by ypid** [debops/ansible-preseed#6]
Hi

I am currently looking into this role. I saw that the APT proxy setting is not configurable but apt_cacher_ng is used by the DebOps project. Am I missing something here? I know that you can also use apt_cacher_ng like it where a mirror. Is that how you do things?

**Comment by drybjed** [comment]
Current situation is like this: `debops.apt` role was planned to be "the one and only" APT role, basically everything around packages, including `apt-cacher-ng`. To configure a host to be an APT proxy you need to specify its FQDN hostname as `apt` variable. Then if this host is the proxy, it configures itself as one, and other hosts basically point to it, if that `apt` variable is in a correct inventory group.

But, after some time, I learned to write better roles and I know now that this choice was a mistake. I want to separate `apt-cacher-ng` and some other tasks to separate roles to make them easier to manage.

As for the proxy configuration in `debops.preseed`, we could add proxy configuration here, sure. I don't see why not. That option existed when the preseeding configuration was part of the `debops.apt` role and used the `apt` variable, but since it was moved to a separate role, I couldn't use that mechanism anymore (no inter-role variable access to preserve idempotency).

**Comment by ypid** [comment]
All right. Thanks. I need to make some other things configurable as well. I will open a PR when I am ready and it is tested.

BTW. Where did you find the `apt-setup/stable-updates` option? When I [Google](http://www.google.de/search?q=%22apt-setup%2Fstable-updates%22) for it, I only find references to your configuration. Did you find that during debugging?

**Comment by drybjed** [comment]
Honestly, I don't remember. I must have seen it in some kind of wiki somewhere, I definitely didn't look through the debian-installer options or anything. Most of the info was taken from around the net.

**Comment by ypid** [comment]
All right. I will play a bit with those settings :smile:
